-- Update unified_contacts view to include premium_score and decision_maker_name
DROP VIEW IF EXISTS public.unified_contacts;

CREATE OR REPLACE VIEW public.unified_contacts AS
SELECT 
    p.id,
    p.email,
    p.full_name,
    p.phone,
    p.user_type::text,
    p.website,
    p.city,
    p.full_address,
    p.postal_code,
    p.street_name,
    p.street_number,
    p.latitude,
    p.longitude,
    p.tags,
    p.is_pro,
    p.referral_code,
    p.marketing_notifications,
    p.push_notifications,
    p.email_notifications,
    COALESCE(p.last_activity, p.created_at) as last_activity,
    p.engagement_score,
    p.created_at,
    p.category,
    p.subcategory,
    'registered' as contact_source,
    p.bio as description,
    p.secondary_emails,
    NULL as company_name,
    (SELECT eo.icebreaker FROM public.email_outbox eo WHERE eo.worker_id = p.id ORDER BY eo.created_at DESC LIMIT 1) as icebreaker,
    (SELECT eo.id FROM public.email_outbox eo WHERE eo.worker_id = p.id ORDER BY eo.created_at DESC LIMIT 1) as outbox_id,
    NULL::integer as premium_score,
    NULL::text as decision_maker_name,
    NULL::text as language
FROM public.profiles p
UNION ALL
SELECT 
    m.id,
    m.email,
    m.full_name,
    m.phone,
    m.user_type,
    m.website,
    m.city,
    m.full_address,
    m.postal_code,
    m.street_name,
    m.street_number,
    m.latitude,
    m.longitude,
    m.tags,
    m.is_pro,
    m.referral_code,
    m.marketing_notifications,
    m.push_notifications,
    m.email_notifications,
    m.last_activity,
    m.engagement_score,
    m.created_at,
    m.category,
    m.subcategory,
    CASE WHEN m.source = 'ai_web_sniper' THEN 'ai_web_sniper' ELSE 'lead' END as contact_source,
    COALESCE(m.company_description, m.description) as description,
    m.secondary_emails,
    m.company_name,
    (SELECT eo.icebreaker FROM public.email_outbox eo WHERE eo.lead_id = m.id ORDER BY eo.created_at DESC LIMIT 1) as icebreaker,
    (SELECT eo.id FROM public.email_outbox eo WHERE eo.lead_id = m.id ORDER BY eo.created_at DESC LIMIT 1) as outbox_id,
    m.premium_score,
    m.decision_maker_name,
    m.language
FROM public.marketing_leads m;

GRANT SELECT ON public.unified_contacts TO authenticated;
